apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-service
  template:
    metadata:
      labels:
        app: sample-service
    spec:
      containers:
      - name: sample-service
        image: nginx:latest
        ports:
        - containerPort: 80